spring.application.name=transpitrack

# Configuration of the SGBD SQLite
spring.datasource.url=jdbc:sqlite:db/transpitrack.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
# Configuration of Hibernate
spring.jpa.database-
platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration upload images
app.upload.users-images-dir=uploads/images/users
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB